sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ryanmarinoff/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ryanmarinoff/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-2-293279730080'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_Access_Key
  secret_access_key: $AWS_Secret_Key