language: node_js
cache: npm

sudo: required
services:
  - docker

before_install:
  - docker build -t ryanmarinoff/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ryanmarinoff/docker-react npm run test